### PR TITLE
Added patch, put, delete

### PR DESCRIPTION
**Pull request by ncthbrt**
Additional Http methods added to bs-express.
Resolves issue #26

### CODE REVIEW

**Comment by ncthbrt** [comment]
@chenglou ping

**Review by glennsl — APPROVED** [review]
This looks good and pretty straightforward to me. It will need @chenglou to be released anyway though, so I'll wait for the second pair of eyes before merging.

**Comment by bassjacob** [comment]
Apologies for the delay, this looks great, thank you 😄

**Comment by bassjacob** [comment]
`bs-express 0.0.6 published` so this should now be available. Please let me know if there are any issues

**Pull request merged**
