### PR TITLE
Use Js_json.classify instead of the deprecated Js.Json.reifyType.

### PR DESCRIPTION
**Pull request by ghost**
When using this package I got the following error:

```
We've found a bug for you! /bs-express/src/express.re 132:19-35

130 ┆ };
131 ┆ let ret = Raw.accepts req types;
132 ┆ let (ty, x) = Js.Json.reifyType ret;
133 ┆ switch ty {
134 ┆ | Js_json.String => Some x

The value reifyType can't be found in Js.Json
```

Looking into the documentation I saw that `Js.Json.reifyType`was deprecated.
https://bucklescript.github.io/bucklescript/api/Js.Json.html#VALreifyType

### CODE REVIEW

**Comment by ghost** [comment]
@bassjacob can you take a look at this please?
The current bindings don't work. Thx!

**Review by bassjacob — APPROVED** [review]
Whoops sorry. Thank you for fixing this :+1:

**Comment by ghost** [comment]
@bassjacob thank you 👍 
Can someone publish this change to npm?

**Comment by bassjacob** [comment]
yes indeed 😄 I'll publish a patch release tonight.

**Comment by bassjacob** [comment]
@marcelofpalves Thanks for reporting this 😄 I've released 0.0.4 which should fix this issue. Please let me know if there are any issues

**Comment by ghost** [comment]
Thank you!
I'll let you know if I find anything.

**Pull request merged**
