### PR TITLE
#76

### PR DESCRIPTION
**Pull request by LaMavia**
1. #76  
1. explicitly define external function names  
1. reorder certain definitions within the interface to match the order in the declaration file  
1. update bs-platform@8.2.0

### CODE REVIEW

**Comment by ncthbrt** [comment]
@DerivedMate Thanks for the PR. Assume you've tested that everything still is working?

**Comment by ncthbrt** [comment]
Are we going to upgrade to use `*.res` files?

**Comment by LaMavia** [comment]
> @DerivedMate Thanks for the PR. Assume you've tested that everything still is working?

I've run the tests, and they've all passed



> Are we going to upgrade to use `*.res` files?

There appear to be some syntax differences, so it'd take a bit of time to rewrite. I can have a go at it at the weekend, though

**Comment by ncthbrt** [comment]
Sounds good to me.

**Comment by LaMavia** [comment]
Nvm, according to [the docs](https://rescript-lang.org/docs/manual/latest/migrate-from-bucklescript-reason#upgrade-your-codebase) it'd be as simple as running ```node_modules/.bin/bsc -format MyFile.re > MyFile.res```

**Pull request merged**
