### PR TITLE
add disable

### PR DESCRIPTION
**Pull request by joprice**
This adds a binding for `disable`: https://expressjs.com/en/api.html#app.disable. It is common to disable this header, among other features using this function: https://stackoverflow.com/questions/10717685/how-to-remove-x-powered-by-in-expressjs. It can also be done with `removeHeader`, which I could also be added to response in another pr.

### CODE REVIEW

**Comment by ncthbrt** [comment]
Hi @joprice, thanks for the PR.
I believe that as far as I can tell, that `Routeable` should not contain the disable function, and it should instead be in the App module (I may be wrong here, but don't see a mention of disable in the Router section of the Express API docs)

**Comment by joprice** [comment]
I just put it in the same place where ‘use’ was defined. I didn’t notice the include in App below. That makes sense. I’ll move it there.

**Comment by joprice** [comment]
@ncthbrt any tip for testing this? I could add a curl that prints the headers and checks that they don't contain 'x-powered-by', but that assumes that the default in express remains 'true'. Not sure if this is accessed at startup or on every request. Maybe I could add 'enable' as well and make an endpoint that mutates it.

**Comment by ncthbrt** [comment]
@joprice Does disable have to be called before startup?

**Review by ncthbrt — APPROVED** [review]

**Comment by joprice** [comment]
I don't see anything in the docs. I'll try it out and check the source.

**Comment by ncthbrt** [comment]
@joprice: If you'd like, can merge this in the mean time.

**Pull request merged**
