### PR TITLE
Use .json instead of .send for sendJson

### PR DESCRIPTION
**Pull request by ryb73**
Per discussion here https://github.com/reasonml-community/bs-express/commit/b8edf6970b999fff2eeadd6dd723a2352dbc6a80#commitcomment-24898169

### CODE REVIEW

**Comment by vramana** [comment]
@ryb73 No need remove external json for now. It can be removed at a later point.

**Comment by ryb73** [comment]
@vramana Sorry, I didn't fully understand – should I put the `external json` back?

**Comment by vramana** [comment]
Yeah

**Comment by bassjacob** [comment]
agreed, then we can merge this 😄

**Pull request merged**
